export const TVSHOW_CONST = {
    FETCH_SCHEDULE : 'FETCH_SCHEDULE',
    FETCH_TVSHOW : 'FETCH_TVSHOW',
    FETCH_SEASONS : 'FETCH_SEASONS',
    SELECT_SEASON : 'SELECT_SEASON',
    SEARCH_TVSHOW : 'SEARCH_TVSHOW'
}

export const TVSHOW_REQUEST_CONST = {
    FETCH_SCHEDULE_REQUESTED: 'FETCH_SCHEDULE_REQUESTED',
    FETCH_TVSHOW_REQUESTED: 'FETCH_TVSHOW_REQUESTED',
    FETCH_SEASONS_REQUESTED: 'FETCH_SEASONS_REQUESTED',
    SELECT_SEASON_REQUESTED: 'SELECT_SEASON_REQUESTED',
    SEARCH_TVSHOW_REQUESTED: 'SEARCH_TVSHOW_REQUESTED'
};

export const LOGIN_ACTIONS = {
    LOGIN_SUBMIT : 'LOGIN_SUBMIT',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGOUT_REQUESTED : 'LOGOUT_REQUESTED',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    INITIAL_AUTH : 'INITIAL_AUTH',
}

export const FAVORITES = {
    ADD_FAVORITE : 'ADD_FAVORITE',
}
