export const TVSHOW_CONST = {
    FETCH_SCHEDULE : 'FETCH_SCHEDULE',
    FETCH_TVSHOW : 'FETCH_TVSHOW',
    FETCH_SEASONS : 'FETCH_SEASONS',
    SELECT_SEASON : 'SELECT_SEASON',
    SEARCH_TVSHOW : 'SEARCH_TVSHOW'
}
